name: gglasso_env

dependencies:
  - python>=3.9
  - numpy>=1.19.2, <2.0.0
  - numba>=0.53.1, <0.60.0
  - scipy>=0.11.0
  - scikit-learn>=0.24.1
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - sphinx
  - pytest
  - pip
  - pip:
    - regain
    - scikit-fda
    - sphinx-gallery
    - sphinx_rtd_theme