name: gglasso_env

dependencies:
  - python>=3.8
  - numpy>=1.19.2
  - numba>=0.53.1
  - scipy>=0.11.0
  - scikit-learn>=0.24.1
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - regain
  - decorator==4.4.2
  - sphinx==3.5.4
  - pytest
  - pip
  - pip:
    - scikit-fda
    - sphinx-gallery==0.8.2
    - sphinx_rtd_theme==0.5.2
    - fdasrsf==2.3.11
  