package:
  name: "gglasso"
  version: "0.1.9"
about:
  summary: "Algorithms for Single and Multiple Graphical Lasso problems."
requirements:
  build:
    - python={{ python_version }}
    - setuptools
    - pip
    - numpy>=1.17.3
    - scipy>=0.11.0
    - scikit-learn>=0.24.1
    - numba>=0.46.0
    - pandas
    - matplotlib
    - seaborn
    - networkx
    - decorator==4.4.2

  run:
    - python={{ python_version }}
    - numpy>=1.17.3
    - scipy>=0.11.0
    - scikit-learn>=0.24.1
    - numba>=0.46.0
    - pandas
    - matplotlib
    - seaborn
    - networkx
    - decorator==4.4.2

source:
  path: ..
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py{{ python_version | replace(".", "") }}