name: Testing

on:
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gglasso_env
          environment-file: environment.yml
          python-version: 3.8
      
      # Install package and run tests
      - name: run tests
        run: |
          pip install -e .
          pip install pytest
          pytest gglasso/tests -v