name: Testing

on:
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        run: |
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env create --file environment.yml
          conda activate gglasso_env
      
      # Install package and run tests
      - name: Test with pytest
        run: |
          python setup.py clean --all develop clean --all